# Generated by Django 3.2.8 on 2021-10-08 11:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Project name')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Project website')),
                ('url_is_active', models.BooleanField(default=False, verbose_name='Website is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('is_private', models.BooleanField(default=True, verbose_name='Private')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_projects', to=settings.AUTH_USER_MODEL)),
                ('industries', models.ManyToManyField(to='projects.Industry')),
                ('technologies', models.ManyToManyField(to='projects.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Company name')),
                ('logo', models.ImageField(upload_to='company_logos/', verbose_name='Company logo')),
                ('year_founded', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2021)])),
                ('website', models.URLField(verbose_name='Company website')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Contact email')),
                ('slogan', models.CharField(max_length=255, verbose_name='Company slogan')),
                ('description', models.TextField(verbose_name='Description')),
                ('founder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
