# Generated by Django 3.2.8 on 2021-11-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211108_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(upload_to='csv_files'),
        ),
    ]
