# Generated by Django 3.2.8 on 2021-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_csvfile_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='Project is private'),
        ),
    ]
