# Generated by Django 3.2.8 on 2021-11-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original',
            field=models.BooleanField(default=True, verbose_name='Project is original'),
        ),
    ]
