# Generated by Django 3.2.8 on 2021-11-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Sets'},
        ),
    ]
