# Generated by Django 3.2.8 on 2021-11-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_set_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='original',
            new_name='is_original',
        ),
    ]
