# Generated by Django 3.2.8 on 2021-11-22 15:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20211119_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetSharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Shared link')),
                ('ip_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=list, size=None)),
                ('opening_counter', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_shared_link', to='projects.set')),
            ],
            options={
                'verbose_name_plural': 'Sets Shared Links',
            },
        ),
    ]
