# Generated by Django 3.2.8 on 2022-11-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_setsharedlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
