# Generated by Django 3.2.8 on 2022-11-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setsharedlink',
            old_name='opening_counter',
            new_name='link_open_counter',
        ),
    ]
