# Here is a random demo data for generating random projects

random_industries = [
    'Media Production',
    'Computer & Network Security',
    'Publishing',
    'Judiciary',
    'Printing',
    'Information Technology & Services',
    'Commercial Real Estate',
    'Motion Pictures & Film',
    'Pharmaceuticals',
    'Investment Management',
    'Education Management',
    'Translation & Localization',
    'Libraries',
    'Internet',
    'Package/Freight Delivery',
    'Program Development',
    'Recreational',
    'Industrial Automation',
    'Fine Art',
    'Maritime',
]
random_technologies = [
    'Javascript',
    'Python',
    'Ruby',
    'PHP',
    'Java',
    'C#',
    'HTML',
    'Elixir',
    'Lastly, Scala',
    'Angular.js',
    'Ember.js',
    'Backbone.js',
    'Express.js',
    'Vue.js',
    'Apache Web Server',
    'Nginx Web Server',
    'IIS Web Server',
    'LiteSpeed Web Server',
]
