random_industries = [
    'Media Production',
    'Computer & Network Security',
    'Publishing',
    'Judiciary',
    'Printing',
    'Information Technology & Services',
    'Commercial Real Estate',
    'Motion Pictures & Film',
    'Pharmaceuticals',
    'Investment Management',
    'Education Management',
    'Translation & Localization',
    'Libraries',
    'Internet',
    'Package/Freight Delivery',
    'Program Development',
    'Recreational',
    'Industrial Automation',
    'Fine Art',
    'Maritime',
]
