random_technologies = [
    'Javascript',
    'Python',
    'Ruby',
    'PHP',
    'Java',
    'C#',
    'HTML',
    'Elixir',
    'Lastly, Scala',
    'Angular.js',
    'Ember.js',
    'Backbone.js',
    'Express.js',
    'Vue.js',
    'Apache Web Server',
    'Nginx Web Server',
    'IIS Web Server',
    'LiteSpeed Web Server',
]
